version: "3.8"

services:
  procrastdb:
    image: ismacaulay/procrastdb:0.1.0
    volumes:
      - ./data/procrastdb/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  userdb:
    image: ismacaulay/userdb:0.1.1
    volumes:
      - ./data/userdb/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  procrast-api:
    image: ismacaulay/procrast-api:0.1.3
    restart: always
    depends_on:
      - procrastdb
      - userdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      PROCRASTDB_HOST: ${PROCRASTDB_HOST}
      PROCRASTDB_PORT: ${PROCRASTDB_PORT}
      USERDB_HOST: ${USERDB_HOST}
      USERDB_PORT: ${USERDB_PORT}
  proxy:
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/proxy/certs:/certs
    depends_on:
      - procrast-api
